name: Unit and UI Test CI

on:
  push:
    branches: [ Expresso_test ]
  pull_request:
    branches: [ Expresso_test ]

jobs:
  build-and-test:
    name: Build, Unit Test, and UI Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          ndk: false

      - name: Grant Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Android Test APK
        run: ./gradlew assembleAndroidTest

      - name: Start Android Emulator
        run: |
          echo "Starting emulator manually..."
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -gpu off -no-audio -no-boot-anim &
          
          echo "Waiting for emulator to appear..."
          $ANDROID_HOME/platform-tools/adb wait-for-device

          echo "Waiting for emulator to finish booting..."
          until $ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed | grep -m 1 '1'; do
            sleep 1
          done

          echo "Emulator booted successfully. Sleeping additional 30s to ensure full readiness..."
          sleep 30

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest

      - name: Terminate Emulator
        run: $ANDROID_HOME/platform-tools/adb emu kill || true
