name: Unit and UI Test CI

on:
  push:
    branches: [ Expresso_test ]
  pull_request:
    branches: [ Expresso_test ]

jobs:
  build-and-test:
    name: Build, Unit Test, and UI Test
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          components: |
            build-tools;30.0.3
            platform-tools
            emulator
            system-images;android-30;google_apis;x86_64

      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Grant Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK and Android Test APK
        run: ./gradlew :app:assembleDebug :app:assembleAndroidTest

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Start Emulator and Run AndroidTest
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_2
          disable-animations: true
          emulator-options: "-no-window -no-audio -no-boot-anim -gpu swiftshader_indirect"
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/tests/testDebugUnitTest/
            app/build/reports/androidTests/connected/
