name: Espresso Test CI

on:
  push:
    branches: [ Expresso_test ]
  pull_request:
    branches: [ Expresso_test ]

jobs:
  build-and-test:
    name: Build & Run Espresso Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Grant Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Android Test APK
        run: ./gradlew assembleAndroidTest

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel
          script: ./gradlew connectedDebugAndroidTest

