name: Espresso Test CI

on:
  push:
    branches: [ Expresso_test ]
  pull_request:
    branches: [ Expresso_test ]

jobs:
  build-and-test:
    name: Build & Run Espresso Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Android Test APK
        run: ./gradlew assembleAndroidTest

      - name: Install required system image
        run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-31;google_apis;arm64-v8a"

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: arm64-v8a
          profile: pixel
          script: |
            adb wait-for-device
            adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
            ./gradlew connectedDebugAndroidTest

